source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'classifier-reborn'
    gem 'csv'
    gem 'base64'
    gem 'bigdecimal'
    gem 'drb'
    gem 'getoptlong'
    gem 'mutex_m'
    gem 'net-ftp'
    gem 'net-imap'
    gem 'net-pop'
    gem 'net-smtp'
    gem 'observer'
    gem 'open3'
    gem 'pstore'
    gem 'readline'
    gem 'resolv-replace'
    gem 'rinda'
    gem 'syslog'
    gem 'webrick'
    gem 'xmlrpc'
    gem 'zlib'
    gem 'jekyll'
    gem 'jekyll-archives'
    gem 'jekyll-diagrams'
    gem 'jekyll-email-protect'
    gem 'jekyll-feed'
    gem 'jekyll-get-json'
    gem 'jekyll-imagemagick'
    gem 'jekyll-jupyter-notebook'
    gem 'jekyll-link-attributes'
    gem 'jekyll-minifier'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'bibtex-ruby', '~> 6.0'
    gem 'jekyll-sitemap'
    gem 'jekyll-toc'
    gem 'jekyll-twitter-plugin'
    gem 'jemoji'
    gem 'mini_racer'
    gem 'unicode_utils'
    gem 'webrick'
end
group :other_plugins do
    gem 'feedjira'
    gem 'httparty'
end
